# TODO make this work both with a sudo password or with a user/pub key e.g.:
# ansible-playbook -v -i DNS_FOR_TARGET_VM, <MY_PLAYBOOK>.yml \
#   --key-file <PATH_TO>/id_rsa \
#   --extra-vars "cli_input_username=<PUT_YOUR_USERNAME>"
#
# That "-i DNS_FOR_TARGET_VM, " could even be "-i localhost, " but needs the
# extra parameter "--connection=local" combined with the YAML (see below):
# "hosts: all" instead of "hosts: localhost"

---
# ansible-playbook setup-docker.yaml -vvvv --ask-sudo-pass --extra-vars "cli_input_username=<PUT_YOUR_USERNAME>"
- name: Make sure docker is installed and configured
  hosts: localhost
  sudo: yes
  vars:
    user_name: "{{ cli_input_username }}"
  tasks:
  - name: Update repositories cache
    apt:
      update_cache: yes
  - name: Install a list of general utilities
    apt: name={{item}} state=installed
    with_items:
      - git
      - jq
      - ipcalc
  - name: Install a list of packages for docker
    apt: name={{item}} state=installed
    with_items:
      - curl
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - python-pip
  - name: Fetch the *Debian* GPG key for the docker repository
    apt_key:
      url: "https://download.docker.com/linux/ubuntu/gpg"
      state: present
  - name: Add the docker repository to apt
    command: bash -c 'add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"'
  - name: Update repositories cache (with the docker repo now)
    apt:
      update_cache: yes
  - name: Install docker
    apt: name=docker-ce=18.* state=installed
  - name: Install docker-compose
    command: bash -c 'pip install docker-compose==1.9.0' # https://github.com/ansible/ansible/issues/20492
  - name: Install docker-py
    pip:
      name: docker-py # this package is to be able to pull/run docker images
      version: 1.10.6 # https://stackoverflow.com/questions/38181433/ansible-cannot-import-docker-py-even-though-it-is-installed
  # the following group/user is to make sure the docker client does not need sudo
  - group:
      name: docker
      state: present
  - user:
      name: "{{ user_name }}"
      group: docker
