---
# ansible-playbook setup-golang.yaml -vvvv --ask-sudo-pass --extra-vars "cli_input_username=<PUT_YOUR_USERNAME>"

# TODO clean/move a previous version to a dedicated place
# to troubleshoot: `type go` (or `which go` instead)
# before running the following: remove completely the existing version: `sudo rm -rf /usr/local/go`
- name: Make sure Go is installed
  hosts: localhost
  sudo: yes
  vars:
    user_name: "{{ cli_input_username }}"
    go_version: 1.12.1
    go_checksum: 2a3fdabf665496a0db5f41ec6af7a9b15a49fbe71a85a50ca38b1f13a103aeec
  tasks:
  # https://golang.org/dl/
  - name: Download the tar file
    get_url:
      url: https://dl.google.com/go/go{{ go_version }}.linux-amd64.tar.gz
      dest: /home/{{ user_name }}/src/go{{ go_version }}.linux-amd64.tar.gz
      checksum: sha256:{{ go_checksum }}
  - name: Extract Go
    unarchive:
      src: /home/{{ user_name }}/src/go{{ go_version }}.linux-amd64.tar.gz
      dest: /usr/local/
  # - name: Make sure Go is configured
  #   # in ansible 2.3 this `destfile` becomes `path`
  #   lineinfile: destfile=/home/{{ user_name }}/.bashrc line='{{ item.line }}' backup=yes state=present
  #   with_items:
  #     - { line: "export GOROOT=/usr/local/go" }
  #     - { line: "export PATH=$PATH:/usr/local/go/bin" }
  - name: Make sure Go is configured
    blockinfile:
      # in ansible 2.3 this `destfile` becomes `path`
      destfile: /home/{{ user_name }}/.bashrc
      backup: yes
      marker: "# {mark} Golang config"
      block: |
        # the Go configuration details
        export GOROOT=/usr/local/go
        export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
