# To run this playbook:
# `ansible-playbook configure-tv-box.yaml -i 192.168.0.53, -v --extra-vars "ansible_user=root ansible_ssh_pass=coreelec"`
- name: Configure the TV box
  hosts: all
  become: yes
  tasks:
    # https://discourse.coreelec.org/t/witch-device-tree-for-remote-mecool/4925/9
  - name: Setup the IR infrared remote controller for Mecool M8S Pro L
    shell: |
      echo "meson-ir * mecool" > /storage/.config/rc_maps.cfg
  - name: Reboot (to apply the IR config)
    shell: |
      reboot
